# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks :
  - name : configure mongodb
    command : mkdir -p /workspace/data && mongod --dbpath /workspace/data

  - name : install node modules and run server
    init : npm install # runs during prebuild
    command : npm run dev
    
image:
  file: .gitpod.dockerfile

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port : 3000
    onOpen : open-preview

